# apiVersion: v1
# kind: Service
# metadata:
#   name: mysql
#   namespace: quiz-connect
# spec:
#   type: ClusterIP
#   ports:
#     - port: 3306
#       targetPort: 3306
#   selector:
#     app: mysql
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: quiz-connect
spec:
  selector:
    app: mysql
  ports:
    - port: 3306
      targetPort: 3306
