# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: frontend-config
#   namespace: quiz-connect
# data:
#   config.json: |
#     {
#       "apiBaseUrl": "/api"
#     }
apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: quiz-connect
  labels:
    app: frontend
    tier: frontend
data:
  config.json: |
    {
      "apiBaseUrl": "/api"
    }
