apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin
  namespace: quiz-connect
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30801
  selector:
    app: phpmyadmin
