apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uploads-pvc
  namespace: quiz-connect
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: csi-cinder-high-speed   # OVH
  resources:
    requests:
      storage: 5Gi
